import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
// import Navbar from "../components/Navigation/Navbar"
// import Sidebar from "../components/Navigation/Sidebar"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Youtube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${inter.className}`}>
        <div className="pt-[4rem]">
        {children}
        </div>
      </body>
    </html>
  );
}
