import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
// import queryClient from "@/lib/react-query";
import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
// import {ReactQueryDevtools} from "react-query-devtools"
// import Navbar from "../components/Navigation/Navbar"
// import Sidebar from "../components/Navigation/Sidebar"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Youtube Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={`${inter.className}`}>
      <ReactQueryProvider>
        <div className="pt-[4rem]">
        {children}
        </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
